# Generated by Django 5.1.3 on 2025-01-11 12:02

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_category_alter_product_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='category.jpg', null=True, upload_to=core.models.user_directory_path),
        ),
    ]
