# Generated by Django 5.1.3 on 2025-01-13 14:31

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_vendor_date_alter_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='cover_image',
            field=models.ImageField(blank=True, default='vendor.jpg', null=True, upload_to=core.models.user_directory_path),
        ),
    ]
